[workspace]
resolver = "2"
members = [
    "crates/carto-model",
    "crates/carto-store",
    "crates/carto-parse",
    "crates/carto-core",
    "crates/carto-cli",
    "crates/carto-bench",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.80"

[workspace.dependencies]
# internal
carto-model = { path = "crates/carto-model" }
carto-store = { path = "crates/carto-store" }
carto-parse = { path = "crates/carto-parse" }
carto-core = { path = "crates/carto-core" }

# external
anyhow = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
blake3 = "1"
clap = { version = "4", features = ["derive"] }
ignore = "0.4"
walkdir = "2"

[profile.release]
opt-level = 3
lto = "thin"
